services:

  # Tailscale Exit Node
  tailscale:
    image: tailscale/tailscale:latest # Image to be used
    container_name: tailscale-exit-node # Name for local container management
    hostname: tailscale-exit-node # Name used within your Tailscale environment
    environment:
      - TS_AUTHKEY=tskey-auth-<ADD-YOUR-AUTH-KEY-HERE>
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--advertise-exit-node
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/tailscale-exit-node/config:/config
      - ${PWD}/tailscale-exit-node/tailscale-node/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    dns:
      - 1.1.1.1 # Can be changed to your desired DNS provider
    sysctls:
      net.ipv4.ip_forward: 1
      net.ipv6.conf.all.forwarding: 1
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun
    network_mode: bridge
    healthcheck:
      test: ["CMD", "tailscale", "status"] # Check if Tailscale is running
      interval: 1m # How often to perform the check
      timeout: 10s # Time to wait for the check to succeed
      retries: 3 # Number of retries before marking as unhealthy
      start_period: 10s # Time to wait before starting health checks
    restart: unless-stopped