services:

  # Tailscale Sidecar Configuration
  tailscale-plex:
    image: tailscale/tailscale:latest # Image to be used
    container_name: tailscale-plex # Name for local container management
    hostname: plex # Name used within your Tailscale environment
    environment:
      - TS_AUTHKEY=tskey-auth-<ADD-YOUR-AUTH-KEY-HERE>
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve.json # Tailsacale Serve configuration to expose the web interface on your local Tailnet - remove this line if not required
      - TS_USERSPACE=false
    volumes:
      - /home/docker-user/plex/config:/config # Config folder used to store Tailscale files - you may need to change the path
      - /home/docker-user/plex/tailscale-plex/state:/var/lib/tailscale  # Tailscale requirement - you may need to change the path
      - /dev/net/tun:/dev/net/tun # Network configuration for Tailscale to work
    cap_add:
      - net_admin
      - sys_module
    ports:
      - 0.0.0.0:32400:32400 # Binding port 32400 to the local network - may be removed if only exposure to your Tailnet is required
    # If any DNS issues arise, use your preferred DNS provider by uncommenting the config below
    # dns: 
    #   - 1.1.1.1 
    restart: unless-stopped

  # Plex Media Server
  plex:
    image: lscr.io/linuxserver/plex:latest # Image to be used
    network_mode: service:tailscale-plex # Sidecar configuration to route Beszel Hub through Tailscale
    container_name: plex # Name for local container management
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /mnt/plex/library:/config
      - /mnt/plex/tvseries:/tv
      - /mnt/plex/movies:/movies
      - /mnt/plex/mylibrary:/mnt/mylibrary # Mount your own library
    depends_on:
      - tailscale-plex
    restart: unless-stopped