name: Perform markdown linting
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      # - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.gitattributes'
      - '.editorconfig'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      # - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.gitattributes'
      - '.editorconfig'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone this repo
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
        with:
          persist-credentials: false
          
      - name: Lint services
        uses: rvben/rumdl@86694902f916bedaa5e37f024cdc7858929092e6
        with:
          path: "services/"
          config: ".markdownlint.yml"
          report-type: annotations
